# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8530dd8be360ff40e0ef97f5a14fd378b6a71c7279b137b9d558b09039513afd68fbd8261c0e37671c885bdc7266d38bdb47d6d043e35806abb66a31ac7086e

test:
  secret_key_base: 0adacc1c0faf8829b3f24f62f5bb34c0cb80f8071790805251310a52cbc4e90227e3f9b7a04b7f0b85b604f91eea024058b205ec3d6a48d0564f494d855e773f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
